apiVersion: v1
kind: Service
metadata:
  name: demoapp
  namespace: demoapp
  labels:
    app.kubernetes.io/name: demoapp
    kubernetes.azure.com/generator: draft
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: demoapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80