name: Container App CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-deploy:

    runs-on: ubuntu-latest

    env: 
      ACR_NAME: ${{ env.ACR_NAME }}

    steps:
    # checkout the repo
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@main
      
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: ACR Login
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          env
          echo "Logging in to ACR"
          echo "1. ACR_NAME= $ACR_NAME"
          echo "2. ACR_NAME= %ACR_NAME%"
          echo "3. ACR_NAME= $ACR_NAME"
          echo "4. acr_name= %acr_name%"
          echo "5. env.ACR_NAME= ${{ env.ACR_NAME }}"
          az acr login -n $ACR_NAME
      env:
        ACR_NAME: ${{ env.ACR_NAME }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: demoapp
        push: true
        tags: ${{ env.ACR_REGISTRY_SERVER }}/demoapp:${{ github.sha }}

    - name: Deploy or update container app
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az containerapp show --name my-container-app --resource-group ${{ env.RG_NAME }}

          if [ $? -eq 0 ]; then
            az containerapp update -n my-container-app -g ${{ env.RG_NAME }} \
              --image ${{ env.ACR_REGISTRY_SERVER }}/demoapp:${{ github.sha }}
          else
            az containerapp create \
              --name my-container-app \
              --resource-group ${{ env.RG_NAME }} \
              --environment ${{ env.AZURE_CONTAINER_ENVIRONMENT_NAME }} \
              --image ${{ env.ACR_REGISTRY_SERVER }}/demoapp:${{ github.sha }} \
              --target-port 80 \
              --ingress external \
              --query properties.configuration.ingress.fqdn \
              --user-assigned ${{ secrets.ACA_IDENTITY_ID }} \
              --registry-identity ${{ secrets.ACA_IDENTITY_ID }} \
              --registry-server ${{ env.ACR_REGISTRY_SERVER }}
          fi
