name: Container App CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    # checkout the repo
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@main
      
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up Docker
      uses: docker/setup-docker-action@v4

    - name: ACR Login
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az acr login -n ${{ secrets.ACR_NAME }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: demoapp
        push: true
        tags: ${{ secrets.ACR_REGISTRY_SERVER }}/demoapp:${{ github.sha }}

    - name: Deploy or update container app
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az containerapp show --name my-container-app --resource-group ${{ secrets.RG_NAME }}

          if [ $? -eq 0 ]; then
            az containerapp update -n my-container-app -g ${{ secrets.RG_NAME }} \
              --image ${{ secrets.ACR_REGISTRY_SERVER }}/demoapp:${{ github.sha }}
          else
            az containerapp create \
              --name my-container-app \
              --resource-group ${{ secrets.RG_NAME }} \
              --environment ${{ secrets.AZURE_CONTAINER_ENVIRONMENT_NAME }} \
              --image ${{ secrets.ACR_REGISTRY_SERVER }}/demoapp:${{ github.sha }} \
              --target-port 80 \
              --ingress external \
              --query properties.configuration.ingress.fqdn \
              --user-assigned ${{ secrets.ACA_IDENTITY_ID }} \
              --registry-identity ${{ secrets.ACA_IDENTITY_ID }} \
              --registry-server ${{ secrets.ACR_REGISTRY_SERVER }}
          fi
